export const GET_SELECTED_INGREDIENTS = 'GET_SELECTED_INGREDIENTS';
export const SET_SELECTED_INGREDIENTS = 'SET_SELECTED_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';

export const GET_SELECTED_BUN = 'GET_SELECTED_BUN';
export const SET_SELECTED_BUN = 'SET_SELECTED_BUN';
export const ADD_BUN = 'ADD_BUN';
export const DELETE_BUN = 'DELETE_BUN';

export const GET_TOTAL_PRICE = 'GET_TOTAL_PRICE';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';

export const GET_SELECTED_IDS = 'GET_SELECTED_IDS';
export const SET_SELECTED_IDS = 'SET_SELECTED_IDS';