export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';

export const ADD_BUN = 'ADD_BUN';
export const DELETE_BUN = 'DELETE_BUN';

export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';

export const UPDATE_INGREDIENTS_ORDER = 'UPDATE_INGREDIENTS_ORDER';

export const CLEAR_CONSTRUCTOR = 'CLEAR_CONSTRUCTOR';