export const SET_REGISTER_REQUEST: 'SET_REGISTER_REQUEST' = 'SET_REGISTER_REQUEST';
export const SET_REGISTER_SUCCESS: 'SET_REGISTER_SUCCESS' = 'SET_REGISTER_SUCCESS';
export const SET_REGISTER_ERROR: 'SET_REGISTER_ERROR' = 'SET_REGISTER_ERROR';

export const SET_LOGIN_REQUEST: 'SET_LOGIN_REQUEST' = 'SET_LOGIN_REQUEST';
export const SET_LOGIN_SUCCESS: 'SET_LOGIN_SUCCESS' = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR: 'SET_LOGIN_ERROR' = 'SET_LOGIN_ERROR';

export const SET_LOGOUT_REQUEST: 'SET_LOGOUT_REQUEST' = 'SET_LOGOUT_REQUEST';
export const SET_LOGOUT_SUCCESS: 'SET_LOGOUT_SUCCESS' = 'SET_LOGOUT_SUCCESS';
export const SET_LOGOUT_ERROR: 'SET_LOGOUT_ERROR' = 'SET_LOGOUT_ERROR';

export const SET_UPDATE_TOKEN_REQUEST: 'SET_UPDATE_TOKEN_REQUEST' = 'SET_UPDATE_TOKEN_REQUEST';
export const SET_UPDATE_TOKEN_SUCCESS: 'SET_UPDATE_TOKEN_SUCCESS' = 'SET_UPDATE_TOKEN_SUCCESS';
export const SET_UPDATE_TOKEN_ERROR: 'SET_UPDATE_TOKEN_ERROR' = 'SET_UPDATE_TOKEN_ERROR';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_ERROR: 'GET_USER_ERROR' = 'GET_USER_ERROR';

export const SET_USER_REQUEST: 'SET_USER_REQUEST' = 'SET_USER_REQUEST';
export const SET_USER_SUCCESS: 'SET_USER_SUCCESS' = 'SET_USER_SUCCESS';
export const SET_USER_ERROR: 'SET_USER_ERROR' = 'SET_USER_ERROR';