export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_ERROR: 'GET_INGREDIENTS_ERROR' = 'GET_INGREDIENTS_ERROR';

export const SET_CURRENT_INGREDIENT: 'SET_CURRENT_INGREDIENT' = 'SET_CURRENT_INGREDIENT';
export const DELETE_CURRENT_INGREDIENT: 'DELETE_CURRENT_INGREDIENT' = 'DELETE_CURRENT_INGREDIENT';

export const INCREASE_COUNT: 'INCREASE_COUNT' = 'INCREASE_COUNT';
export const DECREASE_COUNT: 'DECREASE_COUNT' = 'DECREASE_COUNT';

export const CLEAR_COUNTS: 'CLEAR_COUNTS' = 'CLEAR_COUNTS';